#!/bin/bash

# --- [0. 设置脚本环境] ---
# 强制脚本以其所在目录为工作目录
cd "$(dirname "$0")/.." # 切换到项目根目录 (假设脚本在 a/b/c，我们切换到 a/b)
echo "当前工作目录: $(pwd)"

# --- [配置变量] ---
DB_NAME="primaspace_dev"
DB_USER="primaspace_user"
DB_PASSWORD=$(openssl rand -base64 16)
FLAG_FILE="postgres-installed.flag"
ENV_FILE=".env"

# --- [安全检查] ---
if [ "$(id -u)" -ne 0 ]; then
  echo "此脚本需要以root或sudo权限执行。"
  exit 1
fi

if [ -f "$FLAG_FILE" ]; then
   echo "PostgreSQL服务似乎已初始化过。脚本退出。"
   exit 0
fi

# --- [1. 安装 PostgreSQL] ---
echo "正在更新软件包列表..."
apt-get update -y
echo "正在安装 PostgreSQL..."
apt-get install -y postgresql postgresql-contrib

# --- [2. 配置远程访问 (可选)] ---
# 动态查找配置文件路径，更具弹性
PG_VERSION=$(psql -V | egrep -o '[0-9]{2,}' | head -n1)
PG_CONF="/etc/postgresql/${PG_VERSION}/main/postgresql.conf"
PG_HBA="/etc/postgresql/${PG_VERSION}/main/pg_hba.conf"

if [ -f "$PG_CONF" ] && [ -f "$PG_HBA" ]; then
    echo "配置 PostgreSQL 允许远程连接..."
    sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" "$PG_CONF"
    # 检查是否已存在该行，避免重复添加
    grep -qxF 'host    all             all             0.0.0.0/0               md5' "$PG_HBA" || echo "host    all             all             0.0.0.0/0               md5" >> "$PG_HBA"
    
    echo "重启 PostgreSQL 服务以应用配置..."
    systemctl restart postgresql
else
    echo "警告: 找不到 PostgreSQL 配置文件，跳过远程访问配置。"
fi

# --- [3. 创建数据库和用户] ---
# 使用 -c 参数执行命令，更简洁
echo "正在创建数据库 '${DB_NAME}' 和用户 '${DB_USER}'..."
sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME};"
sudo -u postgres psql -c "CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';"
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};"
# 授权 schema public (重要!)
sudo -u postgres psql -d ${DB_NAME} -c "GRANT ALL ON SCHEMA public TO ${DB_USER};"


# --- [4. 健壮地更新 .env 文件] ---
echo "正在将数据库凭证更新到 ${ENV_FILE} 文件..."

# 创建一个临时文件
TEMP_ENV=$(mktemp)

# 如果 .env 存在，复制其内容，但排除旧的DB设置
if [ -f "$ENV_FILE" ]; then
    grep -vE '^DB_USER=|^DB_PASSWORD=|^DB_NAME=' "$ENV_FILE" > "$TEMP_ENV"
fi

# 在临时文件的末尾追加新的DB设置
{
    echo ""
    echo "# --- Auto-generated by db-init-pg.sh ---"
    echo "DB_USER=${DB_USER}"
    echo "DB_PASSWORD=${DB_PASSWORD}"
    echo "DB_NAME=${DB_NAME}"
} >> "$TEMP_ENV"

# 用新文件安全地覆盖旧文件
mv "$TEMP_ENV" "$ENV_FILE"
chmod 644 "$ENV_FILE" # 设置合理的权限


# --- [5. 标记完成] ---
touch "$FLAG_FILE"

echo "✅ PostgreSQL 初始化成功！"
echo "   数据库: ${DB_NAME}"
echo "   用户: ${DB_USER}"
echo "   密码: ${DB_PASSWORD} (已更新到 ${ENV_FILE} 文件)"
echo "现在，您可以运行 'poetry run alembic upgrade head' 来创建表结构了。"